# Generated by Django 5.2.8 on 2025-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
