# Generated by Django 5.2.8 on 2025-11-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courses_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollments',
            old_name='student_id',
            new_name='student',
        ),
    ]
