# Generated by Django 5.2.8 on 2025-11-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_course_id_enrollments_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='enrollments',
            new_name='Enrollment',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
