# Generated by Django 5.2.8 on 2025-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_teacher_updated_at_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
